### ISSUE TITLE
Molecule View and large molecules

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#10]
Large molecule structures are cut-off.

![Eicosane](https://user-images.githubusercontent.com/19611569/64267257-615a4400-cf36-11e9-8454-34e02ba50f72.PNG)

Maximising the window loads to total crash of the Molecule View. No structures are printed until restart of the software.

**Comment by eselmeister** [comment]
The issue has been fixed.The part can be maximized in such a case now. Minimize works too now. it was an internal resize problem.

![Bildschirmfoto von 2019-09-07 13-48-08](https://user-images.githubusercontent.com/686671/64474664-4119c780-d178-11e9-9050-4ff8d755a936.png)
![Bildschirmfoto von 2019-09-07 13-48-11](https://user-images.githubusercontent.com/686671/64474665-41b25e00-d178-11e9-8651-3f9f98f0ef82.png)
![Bildschirmfoto von 2019-09-07 13-48-24](https://user-images.githubusercontent.com/686671/64474666-41b25e00-d178-11e9-8445-3cb5fa0eaff6.png)
