### ISSUE TITLE
First derivative peak detector with different options

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#103]
Options in the preferences are:
![pref](https://user-images.githubusercontent.com/19611569/109162722-d21f9c80-7778-11eb-9ef9-578e40b029fa.png)

Options via right click in the chromatogram are:
![indi](https://user-images.githubusercontent.com/19611569/109162763-de0b5e80-7778-11eb-82a9-80f5d4be848d.png)

In the latter there are two addional options: "m/z values to filter" and "Use individual traces".
Bug or feature, for me it is confusing.

**Comment by eselmeister** [comment]
[ChemClipse#550](https://github.com/eclipse/chemclipse/issues/550)
