### ISSUE TITLE
Shifting Y-axis in a chromatogram overlay changes the x-axis units (Mac OS, High Sierra) 

### ISSUE THREAD

**Issue by parkashrawat** [OpenChrom/openchrom#109]
![1](https://user-images.githubusercontent.com/84056119/117909794-7e4f3900-b30d-11eb-9463-83020eedf7cf.JPG)
![2](https://user-images.githubusercontent.com/84056119/117909805-8313ed00-b30d-11eb-8748-f0f621eff134.JPG)

Issue/bug: Shifting Y-axis in a chromatogram overlay changes the x-axis units. It also happens with individual plots while shifting the y-axis. Default settings are not changed.

**Comment by eselmeister** [comment]
@parkashrawat Thanks for reporting. Is the x axis displayed correctly again if you select "Reset 1:1" in the chart via the pop-up menu?

**Comment by parkashrawat** [comment]
> @parkashrawat Thanks for reporting. Is the x axis displayed correctly again if you select "Reset 1:1" in the chart via the pop-up menu?

Yes, after the 1:1 reset the axis shows correctly.

**Comment by eselmeister** [comment]
@parkashrawat Thanks for your report. This is fixed and will be released with the next version.
