### ISSUE TITLE
Remove gridlines in scan chart

### ISSUE THREAD

**Issue by ntnguyen63** [OpenChrom/openchrom#120]
Hello. Is there a way to remove gridlines from mass spectrum graph? The one that is labeled as scan chart? I can remove the grid from the main chromatogram but not the scan chart.

**Comment by eselmeister** [comment]
@ntnguyen63 Thanks for the request. I'll take care of it.

**Comment by eselmeister** [comment]
Solved in ChemClipse. Next release contains this feature.
