### ISSUE TITLE
PeakReviewDirectMSD crashes when the boundary is too wide

### ISSUE THREAD

**Issue by Mailaender** [OpenChrom/openchrom#143]
![Screenshot_20210917_105228](https://user-images.githubusercontent.com/756669/133754509-80202529-8953-4828-871b-7e571be758f4.png)

**Comment by Mailaender** [comment]
Probably caused by 

![Screenshot_20210917_110009](https://user-images.githubusercontent.com/756669/133755612-e591d61a-e9f0-4d08-a437-6552e8e8e811.png)

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2021-10-22 10-02-03](https://user-images.githubusercontent.com/686671/138417443-4099f4d4-f0e9-4367-b459-06399b23d9ce.png)

![Bildschirmfoto von 2021-10-22 10-02-11](https://user-images.githubusercontent.com/686671/138417454-468cf2e7-af37-4141-a2dd-cee3cb5746d9.png)

![Bildschirmfoto von 2021-10-22 10-02-28](https://user-images.githubusercontent.com/686671/138417473-fa84a9cd-2e5a-4280-b1db-57c24135950d.png)

![Bildschirmfoto von 2021-10-22 10-02-34](https://user-images.githubusercontent.com/686671/138417488-256bc089-b917-414f-8845-0285cdbc59cf.png)

![Bildschirmfoto von 2021-10-22 10-02-37](https://user-images.githubusercontent.com/686671/138417497-d9b13108-9ce7-4419-b6f6-ec32ca5c4884.png)

**Comment by eselmeister** [comment]
A new option has been added too: Dynamic Offset

Press `KeyPad "+"` to zoom in and `KeyPad "-"` to zoom out. The zoom offset can be defined in the settings page.
