### ISSUE TITLE
Peak Review UI Delta left/right is not available in the preferences

### ISSUE THREAD

**Issue by Mailaender** [OpenChrom/openchrom#144]
This setting is only available during the operation

![Screenshot_20210917_110009](https://user-images.githubusercontent.com/756669/133755612-e591d61a-e9f0-4d08-a437-6552e8e8e811.png)

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2021-10-23 18-09-33](https://user-images.githubusercontent.com/686671/138563654-671ca23c-015c-4ba7-a401-93aea2325d0a.png)

![Bildschirmfoto von 2021-10-23 18-09-41](https://user-images.githubusercontent.com/686671/138563657-7e88a1cd-f0e7-43d5-a682-2acf69a4253e.png)
