### ISSUE TITLE
Comparison Scan Modus Window blocks right click in tables

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#15]
If the Window for the comparison scan modus is activated it is refreshed every time when clicking in the peak list table or the targets table.
In case of right click in these tables the context menu disappears due to refreshing the comparison scan modus window.
Therefore, the context menu of right clicks are not available.

**Comment by eselmeister** [comment]
Could you supply a screenshot?

**Comment by danield5732** [comment]
Unfortunately not, since the context menu shows up very shortly and disappears again.
Talking about the right click context menu for the peak list table and the targets table.

**Comment by laeubi** [comment]
This is now resolved by https://github.com/eclipse/chemclipse/issues/116
