### ISSUE TITLE
the Bruker file to not be recognized

### ISSUE THREAD

**Issue by TGQgood** [OpenChrom/openchrom#172]
I would like to ask what caused the Bruker file to not be recognized. Area1 is a project generated by build, and area2 is a downloaded project. Thank you!
![1638433263(1)](https://user-images.githubusercontent.com/29923448/144387491-97117b4b-d109-451d-8f1a-688d39e27dc2.jpg)

**Comment by Mailaender** [comment]
Where did you download the files from?

**Comment by TGQgood** [comment]
**### The area1 project is downloaded from gitHub, follow wiki build**
![image](https://user-images.githubusercontent.com/29923448/144400553-444e311b-35d8-4ab5-9d09-0c3b1b7a92f5.png)
![image](https://user-images.githubusercontent.com/29923448/144400766-21a76bef-d35c-4f94-a309-3c629aa453e1.png)

**### The area2 project is downloaded from this page**
![image](https://user-images.githubusercontent.com/29923448/144401423-38297dde-15ce-416d-a76e-c851263b3225.png)

**### I'm using the Windows operating system**

**Comment by Mailaender** [comment]
I see. That is to be expected. See also my change https://github.com/OpenChrom/openchrom/commit/b2698dccfdbf5162c04d8de22a324b456ca0a90a which explains that the Lablicate provided edition contains the proprietary converters.
