### ISSUE TITLE
Identifier NIST-DB issue

### ISSUE THREAD

**Issue by judrosden** [OpenChrom/openchrom#19]
Everything appears to run OK connecting with the NIST DB as I have highlighted peaks in my peak list and run the identifier command. I get a message with a green status bar that it may take a few minutes. No errors are thrown. However the targets view doesn't get populated with any compound ids.

Also it looks like some .HLM files are generated in the NIST directory when I run the program.

![image](https://user-images.githubusercontent.com/56457911/66689640-b4bc6200-ec59-11e9-8002-8c235be77da3.png)

![image](https://user-images.githubusercontent.com/56457911/66689595-7c1c8880-ec59-11e9-910e-60d49273d7fb.png)

![image](https://user-images.githubusercontent.com/56457911/66689767-4926c480-ec5a-11e9-8ada-3f7de1d623ca.png)

I'm using OpenChrom Community Edition   OpenChrom Community Edition (Dalton)	1.3.0.201808081331

And NIST version 2.3

Any ideas what I am missing?

**Comment by kerner1000** [comment]
Hi judrosden, did you try to re-select the chromatogram to trigger a refresh of the peak list?

**Comment by judrosden** [comment]
Hello, Yes, that doesn't seem to make a difference.

Judith Denery
Head of Analytics at Cana
judith@cana.com (510) 473-7317

**Comment by laeubi** [comment]
@judrosden 1.3 is rather old, the upcoming 1.4 release contains several-bugfixes regarding NIST-Integration, can you please try out if you issue is solved there?

You can download it here: https://lablicate.com/platform/openchrom/download

BTW: If you are using NIST-DB at daily work we also offer a more advanced NIST-Integration, it is currently under development but will be available soon as a payed extension in our marketplace, let me know if you are interested in participate in the Beta-Test.

**Comment by kerner1000** [comment]
I assume this is resolved. There is also a wiki entry for nist peak identifier now.
