### ISSUE TITLE
Welcome screen does not close on macOS

### ISSUE THREAD

**Issue by periodicsystem** [OpenChrom/openchrom#213]
Hello, 
I am using OpenChrome/Eclipse on macOS. However, I have problems opening files (GC/MS). I can't drag and drop them into the interface or import them via system path import.
The only thing I can see is this surface. Unfortunately, I can't select anything or the like. When I click on Data Analysis, nothing happens either.

I would be very happy if anyone has any tips or a solution to this problem.

Thanks a lot
<img width="1440" alt="Bildschirmfoto 2022-02-18 um 09 46 07" src="https://user-images.githubusercontent.com/47162994/154648901-bf25d12e-c619-4eae-98b7-24a3fc8e846d.png">
!

**Comment by eselmeister** [comment]
Yep, I sent you a reply already to provide a file for testing purposes.

**Comment by nhadler** [comment]
I have also been having this issue. I'm on an M1 Macbook Air.

**Comment by eselmeister** [comment]
@nhadler Could you send me some files for testing purposes?

**Comment by ethanbass** [comment]
I think this is possible some kind of incompatibility with the m1 architecture rather than an issue with the types of files. Openchrom works fine for me on my old intel macbook, but doesn't run in Rosetta on my new m1 mac. Not sure if the original poster is also on an m1 mac.

**Comment by Mailaender** [comment]
Check the latest version 1.5.0 on https://lablicate.com/platform/openchrom/download which we internally tested on M1 (with Rosetta). We have ARM builds on the agenda, but there is no ETA regarding them. However, we fixed the welcome screen bug. Sorry that it took us that long.

**Comment by ethanbass** [comment]
Success! Thank you. FIY, I had to give the app special permission to execute ```sudo xattr -cr ~/Downloads/Eclipse.app```. It was giving me the dreaded "damaged file error"

**Comment by Mailaender** [comment]
Yes, the executables are not signed, so they end in Gatekeeper's quarantine. There are plans to fix this soonish.
