### ISSUE TITLE
Upgrade to new EJML version

### ISSUE THREAD

**Issue by laeubi** [OpenChrom/openchrom#25]
A new EJML version with package version 0.38.x is available we should check if we can upgrade the NMR module to use this version as it includes some bugfixes and improvements.

@alexstark4 please have a look at this @lorenzgerber might can help with question regarding changed class/package names.

**Comment by alexstark4** [comment]
if that's the case, I'll take a look at it.

**Comment by alexstark4** [comment]
AFAICS, nothing has changed in the parts of the EJML used by the NMR features and everything works without errors.

**Comment by laeubi** [comment]
What do you mean by "nothing changed"? At least the package imports need to be adjusted.

**Comment by alexstark4** [comment]
Maybe I didn't express myself very clearly.

I adjusted the imports org.ejml.data and org.ejml.simple;version from "[0.29.0,0.30.0)"
to "[0.29.0,0.38.0)".

As a result I got no errors in the workspace and the features are working
as they did before. Is this procedure incorrect?

**Comment by laeubi** [comment]
That way you exclude the 38 version leaving everything as is. Minimum version should be 0.38 and maximum should be 39 here `[0.38.0,0.39.0)`

**Comment by alexstark4** [comment]
OK, I messed up with the brackets. I'll check it again.
