### ISSUE TITLE
Rename CDK Identifier Bundle

### ISSUE THREAD

**Issue by eselmeister** [OpenChrom/openchrom#332]
Currently, the bundle is named:
`net.openchrom.chromatogram.msd.identifier.supplier.cdk`

Over the time, it turned out, that the CDK can be used more widely inside of OpenChrom. Hence, the bundle shall be renamed to:
`net.openchrom.xxd.identifier.supplier.cdk`

**Comment by Mailaender** [comment]
It still implements MS only chromatogram identifiers for no good reason.
