### ISSUE TITLE
Mol Weight Calculator - also calculate the formula

### ISSUE THREAD

**Issue by eselmeister** [OpenChrom/openchrom#347]
Calculate additionally the formula if absent.

**Comment by eselmeister** [comment]
Example Styrene:

![Screenshot from 2023-02-24 15-27-35](https://user-images.githubusercontent.com/686671/221206029-154803e1-7cde-47f8-b290-75bd9ff736a1.png)
![Screenshot from 2023-02-24 15-36-06](https://user-images.githubusercontent.com/686671/221206034-48e52156-5f94-46af-a568-b7c49a67e6f1.png)

Example Benzene:

![Screenshot from 2023-02-24 15-35-49](https://user-images.githubusercontent.com/686671/221206081-924ac1c5-43ac-4eb0-b045-a580b19afa0d.png)
![Screenshot from 2023-02-24 15-36-15](https://user-images.githubusercontent.com/686671/221206089-efee2d9e-c2cb-44b2-98a2-0263768b0c28.png)

**Comment by Mailaender** [comment]
Class and function should have been renamed.
