### ISSUE TITLE
DNA Sequence Annotations

### ISSUE THREAD

**Issue by eselmeister** [OpenChrom/openchrom#4]
Put the DNA one letter code above the peak including quality metrics. Should be possible with the greatly enhanced SWT Chart library from the Eclipse Advanced Visualization Project.

**Comment by eselmeister** [comment]
Use official Eclipse SWTChart library:
https://github.com/eclipse/swtchart

**Comment by Mailaender** [comment]
I'd rather keep it at https://github.com/OpenChrom/GeneIdent/issues.
