### ISSUE TITLE
MoleculeView: wrong structures

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#40]
There still seems to be some errors in plotting the molecule structures. 

This is chemically unlikely:
![grafik](https://user-images.githubusercontent.com/19611569/79720483-f00eac00-82e0-11ea-83bd-50cf7059232a.png)

This is wrong:
![grafik](https://user-images.githubusercontent.com/19611569/79720664-45e35400-82e1-11ea-84a7-bfa9591f87fc.png)

Maybe this is liked to #9

**Comment by eselmeister** [comment]
The molecule structures are created using CDK and OPSIN. I'll investigate this.

**Comment by eselmeister** [comment]
An option to type modify the settings and to type in IUPAC names, CAS# and/or SMILES have been added.

![Bildschirmfoto von 2020-04-22 12-15-22](https://user-images.githubusercontent.com/686671/79971161-3fe1a480-8494-11ea-8006-648066db22d4.png)
![Bildschirmfoto von 2020-04-22 12-15-41](https://user-images.githubusercontent.com/686671/79971164-407a3b00-8494-11ea-9e0c-c7be3b9fd318.png)
![Bildschirmfoto von 2020-04-22 12-17-01](https://user-images.githubusercontent.com/686671/79971166-4112d180-8494-11ea-83d7-7c30c1578ff2.png)
![Bildschirmfoto von 2020-04-22 12-19-44](https://user-images.githubusercontent.com/686671/79971169-41ab6800-8494-11ea-9fdf-b1e4c6223bf0.png)

Iminostilbene
256-96-2
C1=CC=C2C(=C1)C=CC3=CC=CC=C3N2
https://pubchem.ncbi.nlm.nih.gov/compound/Iminostilbene#section=InChI-Key

2,2'-Dimethylbiphenyl
605-39-0
CC1=CC=CC=C1C2=CC=CC=C2C
https://pubchem.ncbi.nlm.nih.gov/compound/2_2_-Dimethylbiphenyl#section=2D-Structure

2,2'-Dimethylbiphenyl is still rotated.

**Comment by danield5732** [comment]
Thanks for the improvements and new options!

Just testing: Iminostilbene still has some issues

- SMILES is not calculated for Iminostilbene by Chromatogram Identifier - SMILES Identifier
- Therefore, Iminostilbene still show up with the wrong structure
- If SMILES code is inserted manually it works
- Changing the name to _5H-Dibenz[b,f]azepine_ or _2,2'-Iminostilbene_ leads to the right structure

Seems to be a tricky molecule or name :-)

**Comment by Mailaender** [comment]
https://github.com/OpenChrom/openchrom/pull/105 adds support for Angstrom precise chemical structure data, so this will improve in the near future.
