### ISSUE TITLE
Peak/Scan List: sorting does not work for Width and Name

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#42]
Sorting the Peak/Scan List by clicking on the column header does not work propertly for the column Width and Name. 
The latter only works as aspected if all names are filled.

**Comment by danield5732** [comment]
Feature request: It would be nice if the sorting could keep the order from before. 
Therefore, it would be possible to do combined sortings, e.g. first sort by S/N, second sort by classifier.
This would lead to the list sorted by classifier and within the classifier beeing stil sorted by S/N.

**Comment by eselmeister** [comment]
Sorting by name or width has been fixed. There is currently no standard way for JFace tables to indicate multiple column sorting, see:

https://stackoverflow.com/questions/36542057/sort-jface-tableviewer-by-multiple-columns
https://bugs.eclipse.org/bugs/show_bug.cgi?id=133154
