### ISSUE TITLE
Import CDF with RetentionUnit="s" specified

### ISSUE THREAD

**Issue by avasyanin** [OpenChrom/openchrom#489]
CDF files exported by Chromatec Analytic 2.6 program have RetentionUnit specified as "s", not "seconds", so their time scale after reading by OpenChrom is incorrect. The issue probably can be easily solved by adding "s" to the line 87 of https://github.com/OpenChrom/openchrom/tree/develop/openchrom/plugins/net.openchrom.csd.converter.supplier.cdf/src/net/openchrom/csd/converter/supplier/cdf/io/support/AbstractCDFChromatogramArrayReader.java file:

```
if(unit.equals("seconds") || unit.equals("Seconds")) {
```

Thanks.

**Comment by eselmeister** [comment]
Great, thanks for the hint. Could you share a CDF file for testing purposes?

**Comment by avasyanin** [comment]
Yes, sure.

The file also contains some supporting information which is in an ancient CP1251 (Cyrillics), but actually it is not very important.

[20240327-174018 [169.3] (1).cdf.zip](https://github.com/OpenChrom/openchrom/files/14790727/20240327-174018.169.3.1.cdf.zip)

**Comment by eselmeister** [comment]
@avasyanin Thanks for the file. It has been fixed and will be shipped with the next release, scheduled for Friday, 5th of April.

![Screenshot from 2024-03-30 11-00-07](https://github.com/OpenChrom/openchrom/assets/686671/9737d50b-9d4e-4a25-9c3f-f1ef91cf8b2f)
