### ISSUE TITLE
Adding reference chromatograms in the Chromatogram Editor

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#49]
Selecting a reference chromatogram is done by its filename.
The resulting entries in the drop down menu in the Chromatogram Editor are showing the data name. This is a bit confusing.

Interestingly, the data name is not present in OpenChrom anywhere else as far I can see.
Looking in the header data by toggling the overview mode shows the Data Name in raw files from Chemstation files, but not in .odb files.
Also the date (of measurement) is the date of creating the file in .odb header data.

**Comment by laeubi** [comment]
Reference chromatograms can not only be added via file-selection, so the dataname is used. For example if a file contains more than one Chromatogram (e.g. MSD+CSD Data in Agilent files) the filename would be ambiguous.
I think it would be nice if (when added via ChromatogramEditor) the editor asks for the desired name and set this as the data-name afterwards.
