### ISSUE TITLE
How to convert to java

### ISSUE THREAD

**Issue by jgs-gd** [OpenChrom/openchrom#512]
To.Administrator
Hello sir, I'm Korea web developer. I want to know how to convert your source in spring framework.

Our company have raw,mzML files.

At jsp
Just send mzML files to controller like ajax or just submit

At controller(java)
Ultimately i want to know where the algorithms , dependencies are in your source 

Thank you 
This is my email address
Please contact here swing1714@gmail.com

**Comment by eselmeister** [comment]
Hi @jgs-gd,

we have no experience with the Spring framework. If your company needs a web based solution of OpenChrom, please contact me via [1]. We have developed a solution to process data headless on a server and display the results via a web site. 


[1] https://lablicate.com/about/contact
