### ISSUE TITLE
Batch Process Job editor not appearing.

### ISSUE THREAD

**Issue by johnll56** [OpenChrom/openchrom#514]
Currently trying to batch process some HPLC-DAD chromatograms from a Shimadzu instrument. The program reads them just fine.
However, when I go to Chromatogram -->Batch Process, create a new Project and inside it a new Batch Process Job, i get sent straight to the files and method selection window without seeing the editor. Therefore I cannot select an export folder and when clicking "Execute" something seems to happen but no output files are created.
Running Openchrom v1.5 McLafferty edition.

Please help
![image](https://github.com/OpenChrom/openchrom/assets/74071241/f6b8dbc2-62d4-47fe-a034-a9bf8e084000)

This is the screen I see immediately after creating the Batch Process Job and selecting WSD as my data type. No editor in sight

**Comment by eselmeister** [comment]
@johnll56 Are you able to drag & drop the Shimadzu *.lcd files in the left part of the editor and create new process entries with the green plus button in the right part of the editor?

**Comment by johnll56** [comment]
> @johnll56 Are you able to drag & drop the Shimadzu *.lcd files in the left part of the editor and create new process entries with the green plus button in the right part of the editor?

Yes, and I ended up processing each chromatogram individually by creating a method that made my required modifications and then exported the file. It would still be worth it to check the code because as the original post states, the batch process job editor never appeared. I even tried it in the Data Analysis section (after selecting one wavelength and converting one of my .lcd files to .ocb) and it didn't work.

**Comment by eselmeister** [comment]
Could you provide some *.lcd files for testing purposes?

**Comment by johnll56** [comment]
> Could you provide some *.lcd files for testing purposes?

Sure, here are a couple. Uploading as .zip file with no password as Github doesn't support .lcd attachments. Files named 1-3 are from the calibration curve I had to construct as part of the experiment and files 4-6 were obtained from actual biological samples.
[lcd chromatograms.zip](https://github.com/user-attachments/files/16143834/lcd.chromatograms.zip)

Thanks. Hopefully you can also reproduce the bug.

**Comment by eselmeister** [comment]
@johnll56 The batch process works fine on my side. Keep in mind to select "WSD" as an option when creating the batch process and to install the Shimadzu *.lcd converter accordingly.

![Screenshot from 2024-07-12 12-56-40](https://github.com/user-attachments/assets/894bcb68-7974-4e03-9c7d-8a88282b2a21)
![Screenshot from 2024-07-12 12-56-55](https://github.com/user-attachments/assets/ff383751-9164-4285-b6c2-9d41472b73c5)
![Screenshot from 2024-07-12 12-58-00](https://github.com/user-attachments/assets/964b8513-1537-499f-99eb-d8ae67a21605)

**Comment by johnll56** [comment]
Thanks for checking, might have been a Java bug on my end or something.
