### ISSUE TITLE
"Create Retention Index File" menu entry grayed out

### ISSUE THREAD

**Issue by concifederico** [OpenChrom/openchrom#523]
Hi,
Can't make it enabled, no matters what I do. ver. 1.5.0.20220617

![imagen](https://github.com/user-attachments/assets/31ea31d0-823d-4857-b5ff-c84228c36f90)

Any help will be appreciated.
Regards,

Federico

**Comment by eselmeister** [comment]
@concifederico Please provide your raw file for demo purposes.

**Comment by concifederico** [comment]
[std alkanos 140823.raw.zip](https://github.com/user-attachments/files/16462621/std.alkanos.140823.raw.zip)

Here we go!

**Comment by eselmeister** [comment]
Thanks for the file. I can't reproduce it.
![Screenshot from 2024-08-05 06-09-38](https://github.com/user-attachments/assets/d36d0db5-0e83-4103-a954-2c3e90f54a9c)

**Comment by eselmeister** [comment]
If you're a student, get a free license to use our "Power Tools" to easily create RI *.cal files:
https://lablicate.com/marketplace/extensions/powertools

![Screenshot from 2024-08-05 06-05-40](https://github.com/user-attachments/assets/3fe437d2-3a68-4d48-af1e-b83ebb0a4e67)
![Screenshot from 2024-08-05 06-05-47](https://github.com/user-attachments/assets/e9b6deab-2abd-4a49-b07a-84682ec04037)
