### ISSUE TITLE
Tandem MS analyses: Missing information about selected precursor ions

### ISSUE THREAD

**Issue by LouisPM** [OpenChrom/openchrom#530]
Dear _OpenChrom_ developers,

_ChemClipse_ seems to support the import of _.mzML_ files originating from tandem MS analyses. And in _OpenChrom_, 'Filters' enable one to split tandem MS data into chromatograms and ion scans according the level of the MS analysis.

However, information about the precursor ion that was selected for fragmentation seems nowhere to be found. For example, consider an MS/MS analysis, where precursor ions (MS1) had been selected for fragmentation, and scans of their respective fragment ions (MS2) have been recorded. In order to make sense of the MS2 spectra, ones needs information about the respective precursor ion, most crucially its _m/z_ value.

I suggest to add the precursor _m/z_ to both, the window "Chromatogram Scan Info" (_e.g._ as an additional table column), and to the window "Scan Chart" in the line shown upon clicking on the option "Show additional information." In case this information is missing, one could default to al null value or NaN.

It appears that the precursor ion _m/z_ information is described within _.mzML_ headers. Here is an example excerpt for an MS2 scan:

```
<precursorList count="1">
           [...]
                  <cvParam cvRef="MS" accession="MS:1000744" value="387.686004638672" name="selected ion m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
           [...]
 </precursorList>
```

**Comment by Mailaender** [comment]
Can you share an example file?

**Comment by LouisPM** [comment]
The files I have at hand would be to large for an upload on _GitHub_.
Instead, I sent you an invite to a private repository containing a download link.
Let me know once you managed to download the file.

**Comment by Mailaender** [comment]
I could download them.
