### ISSUE TITLE
Feature request for a Peak Filter adding text to peak names

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#59]
I would appreciate a simple Peak Filter that adds sequential numbering to the peak names in the Peak/Scan List. Options could be:

- add before or after the peak name
- provide opportunity to set fixed signs leading to: A1, A2, A3,... or (1), (2), (3),...

Advantages of this would be:

- peaks become unambiguous by name
- this also would overcome current problems in #55 and #48 
- comparing and merging peaks from different measurements using Templates become more clear

**Comment by Mailaender** [comment]
> Peak Identifier → Numerator

was added on 7 Jul 2021.
