### ISSUE TITLE
EMBL-EBI NCBI BLAST interface

### ISSUE THREAD

**Issue by eselmeister** [OpenChrom/openchrom#6]
The SOPA https://www.ebi.ac.uk/seqdb/confluence/display/WEBSERVICES/EMBL-EBI+Web+Services might be promising. The API seems to be a bit more modern compared to the traditional queued NCBI web blast. I hope for better feedback of remaining time and structured data as return, which would make crafting good UI easier.

**Comment by Mailaender** [comment]
I'd rather keep it at https://github.com/OpenChrom/GeneIdent/issues.
