### ISSUE TITLE
Install Assets Menu item does not open the desired dialog

### ISSUE THREAD

**Issue by laeubi** [OpenChrom/openchrom#73]
If clicking on the button, nothing happens (but works in ChemClipse product without a problem).

**Comment by eselmeister** [comment]
It's an issue of the ChemClipse implementation/documentation.

**Comment by laeubi** [comment]
It still needs to be investigated whats different.

**Comment by laeubi** [comment]
The problems is that the config-reader does not starts-up, configuration service seems missing in openchrom product, will investigate this.
