### ISSUE TITLE
Some {extension} tag do not work properly

### ISSUE THREAD

**Issue by hermitwhite** [OpenChrom/openchrom#85]
The {extension} tag at some file export menu returns a string without a leading dot, while others with. Which make it generate files without extension. For example, "Template Chromatogram Report (*.txt)" has this problem. Also I believe that I encountered same problem some else where.

![Screenshot](https://user-images.githubusercontent.com/5426911/94246935-f881a780-ff4e-11ea-8293-ea516ffda18b.png)
⇓
![Generated files](https://user-images.githubusercontent.com/5426911/94248060-87db8a80-ff50-11ea-8e5c-5187d6a7da3a.png)

**Comment by eselmeister** [comment]
Yep, thanks for reporting. We had this issue with other template methods too:
https://github.com/OpenChrom/openchrom/issues/47

I'll check this.

**Comment by eselmeister** [comment]
This is fixed in the latest version:
https://lablicate.com/platform/openchrom/download

![Bildschirmfoto von 2020-09-26 17-46-34](https://user-images.githubusercontent.com/686671/94344537-62b64d00-0020-11eb-83c0-32403cd1ec35.png)
