### ISSUE TITLE
Time interval incorrect

### ISSUE THREAD

**Issue by hermitwhite** [OpenChrom/openchrom#87]
My files(ClarityChrom *.prm) recorded 25 minutes HPLC datas and became 6.25 minutes in OpenChrom. Nothing lost but seems time interval became quarter of original. Is time interval expected correct automatically, or I have to change it manually?

**Comment by eselmeister** [comment]
@Seiken-2ch Yep, you can edit the scan interval in the settings page:

![Bildschirmfoto von 2020-10-02 08-20-24](https://user-images.githubusercontent.com/686671/94893804-4edb7280-0488-11eb-90e4-5b0139ca5b28.png)

That's definitely a workaround as I didn't figure out yet, where the scan rate of the *.prm measurements is encoded. We don't have own instruments, hence it would be great if you could measure the same sample with different scan rates, e.g.:

* 10 Hz
* 20 Hz
* 50 Hz

I would then try to have a look at the *.prm files and try to figure out, where the scan interval is located.
