### ISSUE TITLE
SMILES is wrong calculated for Iminostilbene

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#9]
This leads to a wrong molecular structure in the Molecule View window.

![Iminostilbene](https://user-images.githubusercontent.com/19611569/64266942-cd887800-cf35-11e9-999f-dbbc2cbcedfe.PNG)

The correct one would be: C1=CC=C2C(=C1)C=CC3=CC=CC=C3N2

**Comment by eselmeister** [comment]
We are using OPSIN to parse the names:
https://opsin.ch.cam.ac.uk

Probably, a bug needs to be filed here:
https://bitbucket.org/dan2097/opsin/src/default/

![Bildschirmfoto von 2019-09-05 08-58-51](https://user-images.githubusercontent.com/686671/64318965-98266d80-cfbb-11e9-9307-487b76aeb7d2.png)

**Comment by eselmeister** [comment]
The used OPSIN library has been updated to version 2.4.0. A warning is generated as shown in the screenshot. Calculating the SMILES is skipped now, if a warning exists.
