### ISSUE TITLE
Sorting files at batch process

### ISSUE THREAD

**Issue by hermitwhite** [OpenChrom/openchrom#90]
Files loaded into batch process will become random order, which make it hard to generate a table. Are there a sorting function for batch file lists?

**Comment by eselmeister** [comment]
@Seiken-2ch Yep, that's a good idea. I'll check this.

**Comment by Mailaender** [comment]
This was added in https://github.com/eclipse/chemclipse/issues/739 a few months ago and is already shipped in the latest version.
