### ISSUE TITLE
Manual peak detection

### ISSUE THREAD

**Issue by Ejtnaj** [OpenChrom/openchrom#98]
Dear OpenChrom-Team,

I started using OpenChrom just recently, and I really like it so far, thank you for all your work! I have a question about peak detection though:
I've been trying to detect peaks manually, but unfortunately I cannot find out how. When I click "Show Peak Detector" a new perspective opens, but my chromatogram doesn't show up in there. Also when I go to Preferences > A) Chromatography/Spectrometry > Peak Detector > Manual Peak Detector, there is no info or options I can select. Do I need to install an additional plugin? I'm using version 1.4.x for Linux as well as Windows, my files are ChemStation files (.ch), and I use a DAD. I would be very happy if you could help me and tell me what I'm doing wrong.
Best regards,

Ejtnaj

**Comment by eselmeister** [comment]
@Ejtnaj Please provide some test files via Lablicate. First contact us via the contact form. Then I'll create a share folder.
https://lablicate.com/about/contact

**Comment by eselmeister** [comment]
@Ejtnaj I have added a template/manual peak detector for UV/Vis and DAD. Currently, it uses the TIC. An option to specify traces exists, but this is not enabled yet. Functionality will follow.

![Bildschirmfoto von 2021-02-24 08-08-30](https://user-images.githubusercontent.com/686671/108961606-e2038780-7677-11eb-994e-0cd1cc94f89f.png)

![Bildschirmfoto von 2021-02-24 08-08-45](https://user-images.githubusercontent.com/686671/108961625-e62fa500-7677-11eb-947e-b46d915b8bc9.png)

![Bildschirmfoto von 2021-02-24 08-09-14](https://user-images.githubusercontent.com/686671/108961634-e9c32c00-7677-11eb-84a2-6b150d1a08cf.png)

![Bildschirmfoto von 2021-02-24 08-09-21](https://user-images.githubusercontent.com/686671/108961645-ecbe1c80-7677-11eb-9716-c7e52307140d.png)

A new version will be available in ~2 hours.
